import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;
import java.sql.*;


public class ShowPersonServlet extends HttpServlet {
  //Process the HTTP Get request
public void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

    
    PrintWriter out = response.getWriter();    
    out.println("<html>");
    out.println("<head><title>Show Person</title></head>");
    out.println("<body bgcolor=\"#ffffff\">");
   
    String key = (String)request.getAttribute("key");
	 
 
    PrintWriter out1 = response.getWriter();
 
   //out1.println("<html><body>Output generated by second servlet. <br>"); 
  // out1.println("Name obtained from first servlet is <b>" +key+ "</b><br><body></html>");
    PersonDAO temp = new PersonDAO();
    PersonInfo per= temp.SearchPerson(key);
    if(per.GetN()!="")
    {
      out.println("<p><b>Name: </b>"+per.GetN()+"<p>");
      out.println("<p><b>Address: </b>"+per.GetA()+"<p>");
      out.println("<p><b>Phone: </b>"+per.GetP()+"<p>");

    }
    else
    {
      out.println("<h3>Record does not Exist</h3>");
    }
    out.println("<button onclick=window.location.href='http://localhost:8080/lab_13/search.html'>Search Record</button>");

    

  }

}